import re

from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from rich.console import Console

from utils import print_llm_result

load_dotenv()
console = Console()

# Prompt chaining: one task broken into three calls, where the output of each
# step becomes the input of the next. Each link can run on a different model,
# so the chain pays for the expensive one only where the task needs it.
MODEL_SCHEMA = "gpt-3.5-turbo"
MODEL_ROUTES = "gpt-5-mini"
MODEL_COMMIT = "gpt-4o-mini"

# temperature=0 keeps runs comparable, so differences come from the prompt
llm_schema = ChatOpenAI(model=MODEL_SCHEMA, temperature=0)
# reasoning model: does not accept a custom temperature
llm_routes = ChatOpenAI(model=MODEL_ROUTES)
llm_commit = ChatOpenAI(model=MODEL_COMMIT, temperature=0)


# Step 1 is the only one that does not ask for markdown: its output is not shown
# to a human, it is parsed and fed to step 2, so the fence would be noise.
spec_to_schema = PromptTemplate.from_template(
    """You are a senior backend engineer.
From the following product spec, extract a minimal JSON schema with fields and types.
Only return JSON. No commentary.

Spec:
{spec}
"""
)

schema_to_routes = PromptTemplate.from_template(
    """You are a senior Go developer.
Given the JSON schema below, design REST routes and sketch idiomatic Go handlers for CRUD.
Keep it concise, production-oriented, and show code snippets.

Write all the code using markdown code blocks.

Schema JSON:
{schema_json}
"""
)

commit_message = PromptTemplate.from_template(
    """You are a pragmatic developer.
Write a single-line conventional commit message summarizing the new API based on the schema and routes.

Schema:
{schema_json}

Routes and handlers:
{routes}
"""
)


FENCE = re.compile(r"^\s*```(?:\w+)?\s*\n(.*?)\n\s*```\s*$", re.DOTALL)


def strip_fence(text):
    """Drop a surrounding markdown code fence, if the model added one anyway."""
    match = FENCE.match(text)
    return match.group(1).strip() if match else text.strip()


def run_step(prompt_template, llm, **values):
    """Render the prompt, call the model, print it, and return the response."""
    prompt = prompt_template.format(**values)
    response = llm.invoke(prompt)
    print_llm_result(prompt, response)
    return response


spec_text = """We need a Products API.
Fields: id (uuid), name (string, required), description (string), price (float, > 0), stock (int, >= 0).
We must support list with pagination, create, get by id, update, delete.
"""

# The chain: spec -> schema -> routes -> commit message. Every step but the
# first reads what the previous one wrote, so a bad link poisons the rest.
schema_response = run_step(spec_to_schema, llm_schema, spec=spec_text)
schema_json = strip_fence(schema_response.content)

routes_response = run_step(schema_to_routes, llm_routes, schema_json=schema_json)
routes = routes_response.content

commit_response = run_step(
    commit_message, llm_commit, schema_json=schema_json, routes=routes
)
commit = commit_response.content.strip()


# The input tokens of each step are the output of the one before it: the commit
# message costs a whole page of Go handlers to write a single line.
console.print("[bold]Chain cost per step:[/bold]")
steps = [
    ("schema", MODEL_SCHEMA, schema_response),
    ("routes", MODEL_ROUTES, routes_response),
    ("commit", MODEL_COMMIT, commit_response),
]
for name, model, response in steps:
    usage = getattr(response, "usage_metadata", None) or {}
    console.print(
        f"  {name:<7} [bright_black]{model:<14}[/bright_black] "
        f"in={usage.get('input_tokens', '?')} out={usage.get('output_tokens', '?')}"
    )


result_content = f"""# Prompt Chaining Result

## SCHEMA (Generated by {MODEL_SCHEMA})
```json
{schema_json}
```

## ROUTES & HANDLERS (Go) (Generated by {MODEL_ROUTES})
{routes}

## COMMIT (Generated by {MODEL_COMMIT})
{commit}

---
**Pipeline Models:**
- Step 1: {MODEL_SCHEMA}
- Step 2: {MODEL_ROUTES}
- Step 3: {MODEL_COMMIT}
"""

with open("prompt_chaining_result.md", "w", encoding="utf-8") as f:
    f.write(result_content)

console.print("[bold green]Result saved to prompt_chaining_result.md[/bold green]")
